name: ATRIA-POIN-RUNNER-PROD

on:
  workflow_run:
    workflows: ["ATRIA-POIN-MICROSERVICE-SERVER-CI-PROD"]
    types:
      - completed

jobs:
  build:
    runs-on: POIN-RUNNER-PROD

    steps:
      - name: pull docker container
        run: sudo docker pull resya202/atria-poin-microservice-server-prod:latest

      - name: delete old docker container
        run: sudo docker rm -f atria-poin-container-prod || true
      
      - name: prune unused docker volumes
        run: sudo docker system prune --volumes --force

      - name: run docker container
        run: sudo docker run -d -p 3330:3330 --name atria-poin-container-prod resya202/atria-poin-microservice-server-prod:latest