name: ATRIA-POIN-MICROSERVICE-SERVER-CI-PROD

on:
    push:
      branches:
        - deploy-prod  # This will trigger the CI on pushes to the 'prod' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


    - name: Build Docker Image
      run: docker build -t resya202/atria-poin-microservice-server-prod:latest .
  
    - name: Push Docker Image to Docker Hub
      run: docker push resya202/atria-poin-microservice-server-prod:latest
        